language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
before_install:
  - wget https://github.com/wohldad/AI-Genetic-Parallel-Individual/archive/master.zip -O /tmp/individual.zip
  - unzip /tmp/individual.tar.gz
  - cd /tmp/AI-Genetic-Parallel-Individual-master
  - perl Makefile.PL & make & make test & make install & make clean
script: "perl Makefile.PL && make disttest"
